name: Scrape Data Science Jobs every 12 hours

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch: # {}

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.8'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: |
          python scraper.py

      - name: Generate dashboard HTML
        run: python dashboard.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Data_Science_Jobs_Israel.csv jobs_dashboard.html
          git diff --cached --quiet || git commit -m "Update jobs data and dashboard"
          git push

      - name: Show runner time & event
        run: |
          echo "Runner UTC: $(date -u)"
          echo "Workflow event: $GITHUB_EVENT_NAME"
